permalink: "/:categories/:title:output_ext"
url: "https://daves.blog"

host: "0.0.0.0"
autoreload: true

online:
  web:      "https://daves.blog"
  github:   "dchssr" # https://github.com/{{ online.github }}
  linkedin: "dchssr" # https://linkedin.com/in/{{ online.linkedin }}
  bluesky:  "daves.blog" # https://bsky.app/profile/{{ online.bluesky }}
  irc:
    libera.chat: "deaches"
