permalink: "/:categories/:title:output_ext"
url: "https://daves.blog"

host: "0.0.0.0"
autoreload: true

online:
  github:
    name: "dchssr"
    link: "https://github.com/dchssr"
  linkedin:
    name: "dchssr"
    link: "https://linkedin.com/in/dchssr"
